"""empty message

Revision ID: 677f942f7ffa
Revises: 1356cbb9ed38
Create Date: 2020-08-19 22:48:29.725325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677f942f7ffa'
down_revision = '1356cbb9ed38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_scheme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('grade_scheme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_scheme_id'], ['grading_scheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('institution_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_type_id'], ['institution_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('education_level_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('institution_type_id', sa.Integer(), nullable=True),
    sa.Column('grading_scheme_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('school_address', sa.String(), nullable=True),
    sa.Column('student_number', sa.String(), nullable=True),
    sa.Column('most_recent', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_level.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['grading_scheme_id'], ['grading_scheme.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['institution_type_id'], ['institution_type.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    op.drop_table('institution')
    op.drop_table('grade')
    op.drop_table('institution_type')
    op.drop_table('grading_scheme')
    op.drop_table('education_level')
    # ### end Alembic commands ###
