"""empty message

Revision ID: 6d476ca2c239
Revises: 677f942f7ffa
Create Date: 2020-08-20 21:35:31.618117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d476ca2c239'
down_revision = '677f942f7ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantitative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank_percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verbal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_test_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('verbal_id', sa.Integer(), nullable=True),
    sa.Column('verbal_rank_id', sa.Integer(), nullable=True),
    sa.Column('quantitative_id', sa.Integer(), nullable=True),
    sa.Column('quantitative_rank_id', sa.Integer(), nullable=True),
    sa.Column('writing_id', sa.Integer(), nullable=True),
    sa.Column('writing_rank_id', sa.Integer(), nullable=True),
    sa.Column('total_id', sa.Integer(), nullable=True),
    sa.Column('total_rank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['quantitative_id'], ['quantitative.id'], ),
    sa.ForeignKeyConstraint(['quantitative_rank_id'], ['rank.id'], ),
    sa.ForeignKeyConstraint(['total_id'], ['total.id'], ),
    sa.ForeignKeyConstraint(['total_rank_id'], ['rank.id'], ),
    sa.ForeignKeyConstraint(['verbal_id'], ['verbal.id'], ),
    sa.ForeignKeyConstraint(['verbal_rank_id'], ['rank.id'], ),
    sa.ForeignKeyConstraint(['writing_id'], ['writing.id'], ),
    sa.ForeignKeyConstraint(['writing_rank_id'], ['rank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_test_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('listening_id', sa.Integer(), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('writing_id', sa.Integer(), nullable=True),
    sa.Column('speaking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listening_id'], ['listening.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ),
    sa.ForeignKeyConstraint(['speaking_id'], ['speaking.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['language_test.id'], ),
    sa.ForeignKeyConstraint(['writing_id'], ['writing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_test_score')
    op.drop_table('exam_test_score')
    op.drop_table('writing')
    op.drop_table('verbal')
    op.drop_table('total')
    op.drop_table('speaking')
    op.drop_table('reading')
    op.drop_table('rank')
    op.drop_table('quantitative')
    op.drop_table('listening')
    op.drop_table('language_test')
    op.drop_table('exam')
    # ### end Alembic commands ###
