"""empty message

Revision ID: 99c96ae6a410
Revises: fc067c077468
Create Date: 2020-09-03 12:13:03.220170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c96ae6a410'
down_revision = 'fc067c077468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('language_test_score_speaking_id_fkey', 'language_test_score', type_='foreignkey')
    op.drop_constraint('language_test_score_reading_id_fkey', 'language_test_score', type_='foreignkey')
    op.drop_constraint('language_test_score_listening_id_fkey', 'language_test_score', type_='foreignkey')
    op.drop_constraint('language_test_score_writing_id_fkey', 'language_test_score', type_='foreignkey')
    op.drop_constraint('language_test_score_test_id_fkey', 'language_test_score', type_='foreignkey')
    op.drop_column('language_test_score', 'speaking_id')
    op.drop_column('language_test_score', 'test_id')
    op.drop_column('language_test_score', 'writing_id')
    op.drop_column('language_test_score', 'reading_id')
    op.drop_column('language_test_score', 'listening_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_test_score', sa.Column('listening_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_test_score', sa.Column('reading_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_test_score', sa.Column('writing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_test_score', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_test_score', sa.Column('speaking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('language_test_score_test_id_fkey', 'language_test_score', 'language_test', ['test_id'], ['id'])
    op.create_foreign_key('language_test_score_writing_id_fkey', 'language_test_score', 'writing', ['writing_id'], ['id'])
    op.create_foreign_key('language_test_score_listening_id_fkey', 'language_test_score', 'listening', ['listening_id'], ['id'])
    op.create_foreign_key('language_test_score_reading_id_fkey', 'language_test_score', 'reading', ['reading_id'], ['id'])
    op.create_foreign_key('language_test_score_speaking_id_fkey', 'language_test_score', 'speaking', ['speaking_id'], ['id'])
    # ### end Alembic commands ###
