"""empty message

Revision ID: fc067c077468
Revises: a09758231d3f
Create Date: 2020-09-03 11:45:26.848046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc067c077468'
down_revision = 'a09758231d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'phone')
    # ### end Alembic commands ###
